# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\OTPScanWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OTPScanWindow(object):
    def setupUi(self, OTPScanWindow):
        OTPScanWindow.setObjectName("OTPScanWindow")
        OTPScanWindow.resize(235, 287)
        self.gridLayout = QtWidgets.QGridLayout(OTPScanWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(OTPScanWindow)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.labelQR = QtWidgets.QLabel(OTPScanWindow)
        self.labelQR.setText("")
        self.labelQR.setObjectName("labelQR")
        self.gridLayout.addWidget(self.labelQR, 1, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(OTPScanWindow)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 1)

        self.retranslateUi(OTPScanWindow)
        self.buttonBox.accepted.connect(OTPScanWindow.accept)
        self.buttonBox.rejected.connect(OTPScanWindow.reject)
        QtCore.QMetaObject.connectSlotsByName(OTPScanWindow)

    def retranslateUi(self, OTPScanWindow):
        _translate = QtCore.QCoreApplication.translate
        OTPScanWindow.setWindowTitle(_translate("OTPScanWindow", "Dialog"))
        self.label_2.setText(_translate("OTPScanWindow", "OTP 앱에서 스캔하십시오"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OTPScanWindow = QtWidgets.QDialog()
    ui = Ui_OTPScanWindow()
    ui.setupUi(OTPScanWindow)
    OTPScanWindow.show()
    sys.exit(app.exec_())
